Fix: Build failure - Variadic macro without argument
Release mode build failed when kdebug_println is used like this:
`kdebug_println ("Hello");`

Error: 'ISO C99 requires at least one argument for the "..." in a
variadic macro [-Werror]'